warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ie46527.ap-southeast-1

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: northwind_dw
      warehouse: xsmall_wh
      schema: RAW
      threads: 8
      client_session_keep_alive: False