warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: iw05022.ca-central-1.aws

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: warehouse
      warehouse: xsmall_wh
      schema: RAW
      threads: 8
      client_session_keep_alive: False